# Generated by Django 5.2.3 on 2025-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="изображение"
            ),
        ),
    ]
